#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Dec 16, 2021 12:35:49 AM WAT  platform: Windows NT

import sys

try:
    import tkinter as tk
except ImportError:
    print(ImportError.msg)


try:
    import tkinter.ttk as ttk
    py3 = True
except ImportError:
    print(ImportError.msg)


def set_Tk_var():
    global selectedButton
    selectedButton = tk.IntVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import mainApp
    mainApp.vp_start_gui()




